data/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [ 
    url(
        'layouts-and-subscribers', 
        views.show_layouts_and_subscribers,
        name='layouts_and_subscribers',
    ),
    url('add-layout', views.add_layout, name='add_layout'),
    url('add-subscriber', views.add_subscriber, name='add_subscriber'),
    url('sending', views.send_mailing_list, name='sending'),
    url('result', views.get_sending_result, name='result'),
    url('', views.index, name='index'),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('data.urls')),
]

data/models.py
# -*- coding: utf-8 -*-
from django.db import models


class Layout(models.Model):
    OFFICIAL = 'official'
    FORMAL = 'formal'
    GREETING = ((OFFICIAL, 'Официальное'), (FORMAL, 'Формальное'))

    head = models.CharField(max_length=127,verbose_name='Заголовок письма')
    greeting = models.CharField(
        max_length=127,
        choices=GREETING,
        default=OFFICIAL,
        verbose_name='Приветствие',
    )
    text = models.TextField(verbose_name='Текст письма')
    signature = models.CharField(
        max_length=127, 
        blank=True, 
        null=True, 
        verbose_name='Подпись',
    )

    class Meta:
        verbose_name = 'Макет письма'
        verbose_name_plural='Макеты писем'
    
    def __unicode__(self):
        return self.head


class Subscriber(models.Model):
    first_name = models.CharField(max_length=127, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    email = models.EmailField(verbose_name='Электронная почта')

    class Meta:
        verbose_name = 'Подписчик'
        verbose_name_plural='Подписчики'
    
    def __unicode__(self):
        return self.last_name      

data/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import Layout, Subscriber


class LayoutForm(forms.ModelForm):
    class Meta:
        model = Layout
        fields = ('head', 'greeting', 'text', 'signature')


class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = ('first_name', 'last_name', 'email')      


class MailingListForm(forms.Form):
    layout = forms.ModelChoiceField(
        queryset=Layout.objects.all(), 
        label='Макет письма',
    )
    subscribers = forms.ModelMultipleChoiceField(
        queryset=Subscriber.objects.all(),
        label='Подписчики',
    )

data/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect

from .forms import  LayoutForm, SubscriberForm, MailingListForm

from services.mail_list import get_layouts_and_subscribers, process_mailing_list


def index(request):
    form = MailingListForm()
    layouts, subscribers = get_layouts_and_subscribers()
    if not layouts or not subscribers:
        is_sending_ready = False
    else:
        is_sending_ready = True       
    return render(
        request, 
        'index.html', 
        {'form': form, 'is_sending_ready': is_sending_ready}
    )


def send_mailing_list(request):
    form = MailingListForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            layout = form.cleaned_data['layout'] 
            subscribers = form.cleaned_data['subscribers']
            result = process_mailing_list(layout, subscribers)
            set_message_to_session(request, result)
            return redirect('result')
    set_message_to_session(request, 'Некорректный метод запроса!')
    return redirect('result')


def get_sending_result(request):
    message = get_message_from_session(request)
    return render(
        request, 
        'sending_result.html', 
        {'message': message},
    )        


def set_message_to_session(request, message):
    request.session['message'] = message


def get_message_from_session(request):
    if request.session.get('message'):
        message = request.session.get('message')
        del request.session['message']
    else:
        message = None    
    return message 


def show_layouts_and_subscribers(request):
    layouts, subscribers = get_layouts_and_subscribers()
    message = get_message_from_session(request)  
    return render(
        request, 
        'layouts_and_subscribers.html', 
        {'layouts': layouts, 'subscribers': subscribers, 'message': message},
    )


def add_layout(request):
    form = LayoutForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            message = 'Добавлен новый макет письма!'
            set_message_to_session(request, message)
            return redirect('layouts_and_subscribers')
    return render(request, 'add_layout.html', {'form': form})


def add_subscriber(request):
    form = SubscriberForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            message = 'Добавлен новый подписчик!'
            set_message_to_session(request, message)
            return redirect('layouts_and_subscribers')
    return render(request, 'add_subscriber.html', {'form': form})

templates/add_layout.html
{% extends "base.html" %}
{% block title %}Добавление макета письма{% endblock %}
{% block content %}
{% load user_filters %}

    <h1>Добавить макет письма</h1>

    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-body">
                    
                    {% for error in form.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error|escape }}
                    </div>
                    {% endfor %}

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>

                            <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">
                                {{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}
                            </label>

                            <div class="col-md-6">
                                {{ field|add_class:"form-control" }}
                                {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                    {{ field.help_text|safe }}
                                </small>
                                {% endif %}
                            </div>                
                        </div>
                        {% endfor %}

                        <div class="col-md-6 offset-md-4">              
                            <button type="submit" class="btn btn-primary">
                                Добавить
                            </button>
                        </div>
                    </form>
                </div> 
            </div>
        </div>     
    </div>

{% endblock %}

templates/add_subscriber.html
{% extends "base.html" %}
{% block title %}Добавление подписчика{% endblock %}
{% block content %}
{% load user_filters %}

    <h1>Добавить подписчика</h1>

    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-body">
                    
                    {% for error in form.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error|escape }}
                    </div>
                    {% endfor %}

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>

                            <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">
                                {{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}
                            </label>

                            <div class="col-md-6">
                                {{ field|add_class:"form-control" }}
                                {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                    {{ field.help_text|safe }}
                                </small>
                                {% endif %}
                            </div>                
                        </div>
                        {% endfor %}

                        <div class="col-md-6 offset-md-4">              
                            <button type="submit" class="btn btn-primary">
                                Добавить
                            </button>
                        </div>
                    </form>
                </div> 
            </div>
        </div>     
    </div>

{% endblock %}

templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body class="d-flex flex-column min-vh-100">
    {% include 'header.html' %}
    <main class="flex-fill mt-4">
        <div class="container">
            {% block content %}
            <!-- Содержимое страницы -->
            {% endblock %}
        </div>
    </main>
    {% include 'footer.html' %}
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

templates/footer.html
<footer class="navbar justify-content-center bg-dark" style="background-color: #e3f2fd;">
    <p class="my-2 text-white">Тестовое задание, выполнил Докторов Денис</p>
</footer> 

templates/header.html
<header>   
    <nav class="navbar navbar-light bg-dark">
        <a class="navbar-brand text-white" href="{% url 'index' %}">Cервис отправки email рассылок</a>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-white" href="{% url 'layouts_and_subscribers' %}">Макеты писем и подписчики</a>
            <a class="p-2 text-white" href="{% url 'add_layout' %}">Добавить макет письма</a>
            <a class="p-2 text-white" href="{% url 'add_subscriber' %}">Добавить подписчика</a>
        </nav>
    </nav>
</header>   

templates/index.html
{% extends "base.html" %}
{% block title %}Главная страница{% endblock %}
{% block content %}
{% load user_filters %}

    <h1>Отправка рассылки подписчикам</h1>

    {% if not is_sending_ready %}
    <p class="mt-4">Недостаточно данных для отправки рассылки</p>
    <a href="{% url 'layouts_and_subscribers' %}" class="btn btn-primary">
        Посмотреть созданные макеты писем и список доступных подписчиков
    </a>
    {% else %}
    <p class="mt-4">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-body">
                        
                        {% for error in form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error|escape }}
                        </div>
                        {% endfor %}
    
                        <form method="post" action="{% url 'sending' %}">
                            {% csrf_token %}
    
                            {% for field in form %}
                            <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
    
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">
                                    {{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}
                                </label>
    
                                <div class="col-md-6">
                                    {{ field|add_class:"form-control" }}
                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                        {{ field.help_text|safe }}
                                    </small>
                                    {% endif %}
                                </div>                
                            </div>
                            {% endfor %}
    
                            <div class="col-md-6 offset-md-4">              
                                <button type="submit" class="btn btn-primary">
                                    Отправить рассылку
                                </button>
                            </div>
                        </form>
                    </div> 
                </div>
            </div>     
        </div>
    </p>
    {% endif %}

{% endblock %}

templates/layouts_and_subscribers.html
{% extends "base.html" %}
{% block title %}Макеты писем и подписчики{% endblock %}
{% block content %}

    <h1>Макеты писем и подписчики</h1>

    {% if message %}
    <div class="alert alert-success mt-3" role="alert">
        {{ message }}
    </div>
    {% endif %}

    <h4 class="mt-4">Макеты писем</h4>
    {% if layouts %}   
    <table class="table table-secondary mt-3">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Заголовок</th>
                <th scope="col">Приветствие</th>
                <th scope="col">Текст</th>
                <th scope="col">Подпись</th>
            </tr>
        </thead>
        <tbody>

            {% for layout in layouts %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ layout.head }}</td>
                <td>{{ layout.get_greeting_display }}</td>
                <td>{{ layout.text }}</td>
                <td>{{ layout.signature }}</td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
    {% else %}
    <p class="mt-4">Доступных макетов нет.</p>
    <a href="{% url 'add_layout' %}" class="btn btn-primary">
        На страницу добавления макета
    </a>
    {% endif %}


    <h4 class="mt-4">Подписчики</h4>
    {% if subscribers %}   
    <table class="table table-info mt-3 mb-4">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Фамилия</th>
                <th scope="col">Имя</th>
                <th scope="col">Адрес электронной почты</th>
            </tr>
        </thead>
        <tbody>

            {% for subscriber in subscribers %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ subscriber.first_name }}</td>
                <td>{{ subscriber.last_name }}</td>
                <td>{{ subscriber.email }}</td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
    {% else %}
    <p class="mt-4">Доступных макетов нет.</p>
    <a href="{% url 'add_subscriber' %}" class="btn btn-primary">
        На страницу добавления подписчика
    </a>
    {% endif %}

{% endblock %}

templates/layouts_subscribers.html
{% extends "base.html" %}
{% block title %}Макеты писем и подписчики{% endblock %}
{% block content %}

    <h1>Макеты писем и подписчики</h1>

    {% if message %}
    <div class="alert alert-success" role="alert">
        {{ message }}
    </div>
    {% endif %}

    <h4 class="mt-4">Макеты писем</h4>
    {% if layouts %}   
    <table class="table table-secondary mt-3">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Заголовок</th>
                <th scope="col">Приветствие</th>
                <th scope="col">Текст</th>
                <th scope="col">Подпись</th>
            </tr>
        </thead>
        <tbody>

            {% for layout in layouts %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ layout.head }}</td>
                <td>{{ layout.get_greeting_display }}</td>
                <td>{{ layout.text }}</td>
                <td>{{ layout.signature }}</td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
    {% else %}
    <p class="mt-4">Доступных макетов нет.</p>
    <a href="{% url 'add_layout' %}" class="btn btn-primary">
        На страницу добавления макета
    </a>
    {% endif %}


    <h4 class="mt-4">Подписчики</h4>
    {% if subscribers %}   
    <table class="table table-info mt-3 mb-4">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Фамилия</th>
                <th scope="col">Имя</th>
                <th scope="col">Адрес электронной почты</th>
            </tr>
        </thead>
        <tbody>

            {% for subscriber in subscribers %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ subscriber.first_name }}</td>
                <td>{{ subscriber.last_name }}</td>
                <td>{{ subscriber.email }}</td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
    {% else %}
    <p class="mt-4">Доступных макетов нет.</p>
    <a href="{% url 'add_subscriber' %}" class="btn btn-primary">
        На страницу добавления подписчика
    </a>
    {% endif %}

{% endblock %}

templates/sending_result.html
{% extends "base.html" %}
{% block title %}Результат отправки рассылки{% endblock %}
{% block content %}

    <h1>Результат отправки рассылки</h1>

    {% if message %}
    <div class="alert alert-secondary mt-3" role="alert">
        {{ message }}
    </div>
    {% endif %}
  
    <a href="{% url 'index' %}" class="btn btn-primary mt-2">
        На главную
    </a>

{% endblock %}